# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c08e105b1d6cc1499529c1260e930aea5a0447da3237f85b1d149c769250a669407326f8c3fcb2eb8714a6172451e00afb92d0aec4aa06f1fa286eca0241cfd9

test:
  secret_key_base: 15ce578420c1e10a4e3bb3a65cef8112d79a6f1013376b7c5c76ccce564942b74815cca2f3c34d45401e5a07ea025cdf543a7dccf3623c2d57b62c4a39c62194

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
